apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    g, admin, role:admin
    g, developer, role:developer
  roles:
    - name: developer
      description: Developer access
      policies:
        - p, role:developer, applications, get, */*, allow
        - p, role:developer, applications, sync, */*, allow
    - name: admin
      description: Full admin access
      policies:
        - p, role:admin, *, *, *, allow
