name: Sync GitOps Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest image tag from Docker Hub
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/your-dockerhub-username/contact-us/tags/" | jq -r '.results[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Update values.yaml with new image tag
        run: |
          sed -i 's|tag:.*|tag: "'"${{ env.LATEST_TAG }}"'"|' environments/dev/values.yaml
