apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contact-us
spec:
  rules:
    - host: contact-us.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contact-us
                port:
                  number: 80
