apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
patches:
  - target:
      kind: Deployment
      name: contact-us
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: lirangibli/contact-us:latest
