apiVersion: v1
kind: Service
metadata:
  name: contact-us
  namespace: contact-us   # ← שים לב שהשורה הזו קיימת
spec:
  selector:
    app: contact-us
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
